version: '3'
services:
  auth-api:
    image: "asciishell/auth-api:${IMAGE_TAG}"
    env_file: docker.env
    environment:
      - "BASE64_DB_URL=${DB_URL}"
    ports:
      - "8000:8000"
    restart: always